add '-s' in 'poetry run python -m pytest' line in cicd.yml
Adding '-s' in 'poetry run python -m pytest' line in cicd.yml is needed to avoid check error in github.
The error
OSError: pytest: reading from stdin while output is captured!  Consider using `-s`
raised by poetry run python -m because input is used in main.py  to select input args for function.